package org.csc133.a2;



import com.codename1.charts.util.ColorUtil;
import com.codename1.components.ButtonList;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;

import com.codename1.ui.util.UITimer;
import org.csc133.a2.gameobjects.*;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class AppMain extends Lifecycle {
    @Override
    public void runApp() {
        new Game();
    }

}

