package org.csc133.a2;

import static com.codename1.ui.CN.*;

import com.codename1.charts.util.ColorUtil;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;
import com.codename1.ui.util.UITimer;
import org.csc133.a2.gameobjects.Helipad;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class AppMain extends Lifecycle {
    @Override
    public void runApp() {
        new Game();
    }

}
class Game extends Form implements Runnable{
    private GameWorld gw;
    public Game()
    {
        gw = new GameWorld();

        UITimer timer = new UITimer(this);
        this.getAllStyles().setBgColor(ColorUtil.BLACK);
        this.show();
    }


    @Override
    public void run()
    {
        gw.tick();
        repaint();
    }

    public void paint(Graphics g)
    {
        super.paint(g);
        gw.draw(g);
    }

}

class GameWorld
{
    private Helipad helipad;

    public GameWorld()
    {
        init();
    }

    void init()
    {
        helipad = new Helipad();
    }

    void draw(Graphics g)
    {
        helipad.drawHelipad(g);
    }

    public void tick()
    {

    }
}
